// src/components/views/login/Login.vue
<script setup>
import bgLogin from '@/assets/images/login/background.png'

function setCookie(name, value, days) {
    var expires = "";

    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days*24*60*60*1000));
        expires = "; expires=" + date.toUTCString();
    }

    document.cookie = name + "=" + (value || "")  + expires + "; path=/";
}

const submitForm = async (event) => {
    event.preventDefault();

    const form = event.target;

    const data = {
        email: form.email.value,
        password: form.password.value
    }

    const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(data)
    })

    const result = await response.json();
    console.log(result);

    if (!result.success) {
        alert("Email ou mot de passe incorrect");
        return;
    }

    // On sauvegarde le token dans un cookie
    setCookie("token", result.result.token);

    // on redirige vers la page du compte
    window.location = "/me";    
}
</script>

<template>
    <main class="login-page" :style="{
        backgroundImage: `
            url(${bgLogin})
        `
    }">
        <div class="login-container">
            <h1 class="login-title">Mon <span>Compte</span></h1>
            
            <form @submit="submitForm" class="glass-form">
                <div class="input-group">
                    <label>Email</label>
                    <input type="text" name="email" required placeholder="votre@email.com">
                </div>

                <div class="input-group">
                    <label>Mot de passe</label>
                    <input type="password" name="password" required placeholder="••••••••">
                </div>

                <button type="submit" class="btn-pill">Se connecter</button>
                
                <div class="form-footer">
                    <a href="#" class="forgot-pass">Mot de passe oublié ?</a>
                </div>
            </form>
        </div>
    </main>
</template>

<style scoped>
@font-face {
  font-family: 'Magilio';
  src: url('../fonts/Magilio.ttf') format('truetype'),
    url('../fonts/MagilioDEMO.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

.login-page {
    min-height: 100vh;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    padding-top: 80px; 
}

.login-container {
    width: 100%;
    max-width: 450px;
    padding: 2rem;
    text-align: center;
    animation: fadeIn 0.8s ease-out;
}

.login-title {
    font-family: 'Magilio';
    font-size: 3.5rem;
    color: #F9F5F0;
    margin-bottom: 2rem;
    font-weight: 300;
}

.login-title span {
    color: rgb(252, 198, 188);
    font-style: italic;
}

.glass-form {
    background: rgba(255, 255, 255, 0.05);
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 20px;
    padding: 3rem 2.5rem;
    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}

.input-group {
    text-align: left;
}

label {
    display: block;
    font-family: var(--font-sans, 'Montserrat', sans-serif);
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: rgba(249, 245, 240, 0.8);
    margin-bottom: 0.5rem;
}

input {
    width: 100%;
    padding: 12px 0;
    background: transparent;
    border: none;
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);
    color: #fff;
    font-family: var(--font-sans, 'Montserrat', sans-serif);
    font-size: 1rem;
    transition: border-color 0.3s ease;
}

input:focus {
    outline: none;
    border-bottom-color: rgb(252, 198, 188);
}

input::placeholder {
    color: rgba(255, 255, 255, 0.3);
}

.btn-pill {
    margin-top: 1rem;
    padding: 1rem 2.2rem;
    border-radius: 999px;
    background: transparent;
    border: 1.5px solid rgb(252, 198, 188);
    color: rgb(252, 198, 188);
    font-size: 0.9rem;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.3s ease;
}

.btn-pill:hover {
    background: rgb(252, 198, 188);
    color: #2A221E;
    box-shadow: 0 0 15px rgba(252, 198, 188, 0.4);
}

.form-footer {
    margin-top: 0.5rem;
}

.forgot-pass {
    color: rgba(255, 255, 255, 0.5);
    font-size: 0.8rem;
    text-decoration: none;
    transition: color 0.3s;
}

.forgot-pass:hover {
    color: rgb(252, 198, 188);
}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}

@media (max-width: 768px) {
    .login-title {
        font-size: 2.5rem;
    }
    
    .glass-form {
        padding: 2rem 1.5rem;
    }
}
</style>

// src/routes/login/+page.svelte
<script>
	import { fade } from 'svelte/transition';

    // Import images
    import background from '$lib/assets/images/login/background.png';

	// État connexion
	let isLoginMode = true;
	let isLoading = false;
	
	// État pour animation images
	let hoverImage = false;
	let hoverTabs = false;
	let focusTabs = false;
	$: isImageColored = hoverImage || hoverTabs || focusTabs;

	// @ts-ignore
	async function submitLogin(event) {
        // On notifie qu'on est en cours de chargement
		isLoading = true;

        // On capture le form pour récupérer ses données
        const form = event.target;
        const data = {
            email: form.email.value,
            password: form.password.value
        }

        // on fait une requete api pour se log
        const response = await fetch('/api/auth/login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        })

        // On lit le résultat
        const result = await response.json();

        // Si erreur on affiche un message d'erreur et on quitte
        if (!result.success) {
            alert("Email ou mot de passe incorrect");
            return;
        }

        // Fin du chargement
        isLoading = false;

        // Si on a réussit on redirige vers la page de l'utilisateur
		// on utilise window.location.href pour forcer le raffraichissement car goto ne le fait pas
		window.location.href = '/me';  
	}

    // @ts-ignore
	async function submitRegister(event) {
        // On capture le form pour récupérer ses données
        const form = event.target;
        const data = {
            firstname: form.firstname.value,
            lastname: form.lastname.value,
            email: form.email.value,
            password: form.password.value,
            confirmPassword: form.confirmPassword.value
        }

		if (data.password !== data.confirmPassword) {
			alert('Les mots de passe ne correspondent pas');
			return;
		}

        // On notifie qu'on est en cours de chargement
		isLoading = true;

		try {
            // on supprime la confirmation mdp des data
			delete data.confirmPassword;
            
            // To do : faire la requete
		} catch (error) {
			alert(error);
		} finally {

            // Fin du chargement
			isLoading = false;
		}
	}
</script>

<section class="min-h-screen flex items-center justify-center p-6 font-sora overflow-hidden relative">
    <!-- Zone décorative -->
    <!-- Cercle-->
    <div class="absolute top-10 left-10 hidden md:block">
        <div class="w-32 h-32 bg-green-400 border-4 border-black rounded-full shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"></div>
    </div>

    <!-- Etoile -->
    <div class="absolute top-20 right-20 hidden lg:block rotate-12">
        <div class="relative group cursor-default">
            <svg viewBox="0 0 200 200" class="w-48 h-48 drop-shadow-[8px_8px_0px_rgba(0,0,0,1)] text-purple-400 fill-current animate-spin-slow duration-700">
                <path d="M100 0 L125 75 L200 100 L125 125 L100 200 L75 125 L0 100 L75 75 Z" stroke="black" stroke-width="3"/>
            </svg>
            <span class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 font-black text-black text-xl bg-white border-2 border-black px-2 -rotate-12">WOW!</span>
        </div>
    </div>

    <!-- Journal -->
    <div class="absolute bottom-10 left-20 hidden lg:block -rotate-6 z-0">
        <div class="w-40 h-40 border-4 border-black bg-yellow-300 shadow-[12px_12px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center">
            <span class="font-black text-4xl">★</span>
        </div>
    </div>

    <!-- Texte arrière plan -->
    <div class="absolute inset-0 flex items-center justify-center pointer-events-none opacity-5 z-0 overflow-hidden">
        <h1 class="text-[20vw] font-black tracking-tighter leading-none whitespace-nowrap">FRAME LAB</h1>
    </div>

     <!-- Zone central -->
	<div class="relative max-w-5xl w-full mt-10 mb-32 z-10">
        <!-- Mini caré sur le coin haut gauche -->
        <div class="absolute -top-4 -left-4 w-8 h-8 bg-black border-4 border-white z-20"></div>
        
        <!-- Mini caré sur le coin bas droite -->
        <div class="absolute -bottom-4 -right-4 w-8 h-8 bg-black border-4 border-white z-20"></div>
        
        <!-- Container image -->
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<div 
			class="border-8 border-black z-0 relative bg-white shadow-[16px_16px_0px_0px_rgba(0,0,0,1)]"
			on:mouseenter={() => hoverImage = true}
			on:mouseleave={() => hoverImage = false}
		>
			<img
				src={background}
				alt="FrameLab Creation"
				class="w-full h-[420px] object-cover transition-all duration-300 {isImageColored ? '' : 'grayscale'}" 
			/>
		</div>

		<!-- Overlay tab control connexion / création compte -->
		<!-- svelte-ignore a11y_no_static_element_interactions -->
		<div 
			class="absolute left-1/2 -translate-x-1/2 z-10 w-full max-w-[480px]" 
			style="top: 150px;"
			on:mouseenter={() => hoverTabs = true}
			on:mouseleave={() => hoverTabs = false}
			on:focusin={() => focusTabs = true}
			on:focusout={() => focusTabs = false}
		>
			<div class="flex flex-col">
				<div class="flex pl-2 gap-2 translate-y-[3px] z-10">
					<!-- Onglet connexion -->
					<button
						on:click={() => (isLoginMode = true)}
						class="flex-1 py-3 px-4 font-bold uppercase border-t-[3px] border-x-[3px] border-b-0 border-black rounded-t-lg transition-all duration-200 
                        {isLoginMode
							? 'bg-pink-400 -translate-y-1 pb-4 text-black'
							: 'bg-gray-100 text-gray-500 hover:bg-gray-200'}"
					>
						Connexion
					</button>

					<!-- Onglet inscription -->
					<button
						on:click={() => (isLoginMode = false)}
						class="flex-1 py-3 px-4 font-bold uppercase border-t-[3px] border-x-[3px] border-b-0 border-black rounded-t-lg transition-all duration-200 
                        {!isLoginMode
							? 'bg-yellow-300 -translate-y-1 pb-4 text-black'
							: 'bg-gray-100 text-gray-500 hover:bg-gray-200'}"
					>
						Inscription
					</button>
				</div>

				<div class="bg-white border-[3px] border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] p-8 relative z-20">
					{#if isLoginMode}
						<!-- Formulaire connexion -->
						<form
							on:submit|preventDefault={submitLogin}
							in:fade={{ duration: 200 }}
							class="flex flex-col gap-5"
						>
							<div class="space-y-2">
								<label for="email" class="block font-extrabold text-sm uppercase tracking-wide"
									>Email</label
								>
								<input
									type="email"
									name="email"
									required
									placeholder="votre@email.com"
									class="w-full bg-gray-50 border-2 border-black p-3 font-medium placeholder-gray-400 focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] focus:bg-white transition-all"
								/>
							</div>

							<div class="space-y-2">
								<label for="password" class="block font-extrabold text-sm uppercase tracking-wide"
									>Mot de passe</label
								>
								<input
									type="password"
									name="password"
									required
									placeholder="••••••••"
									class="w-full bg-gray-50 border-2 border-black p-3 font-medium placeholder-gray-400 focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] focus:bg-white transition-all"
								/>
							</div>

							<button
								type="submit"
								disabled={isLoading}
								class="mt-4 w-full bg-black text-white font-bold uppercase py-4 border-[3px] border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,0.5)] transition-all duration-200 hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-[1px_1px_0_rgba(0,0,0,1)] hover:bg-green-400 hover:text-black disabled:opacity-50 disabled:cursor-not-allowed"
							>
								{isLoading ? 'Chargement...' : 'Se connecter'}
							</button>
						</form>
					{:else}
						<!-- Formulaire inscription -->
						<form
							on:submit|preventDefault={submitRegister}
							in:fade={{ duration: 200 }}
							class="flex flex-col gap-4"
						>
							<div class="flex gap-4">
								<div class="space-y-2 w-1/2">
									<label for="lastname" class="block font-extrabold text-xs uppercase">Nom</label>
									<input
										type="text"
										name="lastname"
										required
										placeholder="Monsieur"
										class="w-full bg-gray-50 border-2 border-black p-3 text-sm focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
									/>
								</div>
								<div class="space-y-2 w-1/2">
									<label for="firstname" class="block font-extrabold text-xs uppercase"
										>Prénom</label
									>
									<input
										type="text"
										name="firstname"
										required
										placeholder="Dupont"
										class="w-full bg-gray-50 border-2 border-black p-3 text-sm focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
									/>
								</div>
							</div>

							<div class="space-y-2">
								<label for="email" class="block font-extrabold text-xs uppercase">Email</label>
								<input
									type="email"
									name="email"
									required
									placeholder="votre@email.com"
									class="w-full bg-gray-50 border-2 border-black p-3 text-sm focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
								/>
							</div>

							<div class="space-y-2">
								<label for="password" class="block font-extrabold text-xs uppercase"
									>Mot de passe</label
								>
								<input
									type="password"
									name="password"
									required
									placeholder="••••••••"
									class="w-full bg-gray-50 border-2 border-black p-3 text-sm focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
								/>
							</div>

							<div class="space-y-2">
								<label for="confirmPassword" class="block font-extrabold text-xs uppercase"
									>Confirmer</label
								>
								<input
									type="password"
									name="confirmPassword"
									required
									placeholder="••••••••"
									class="w-full bg-gray-50 border-2 border-black p-3 text-sm focus:outline-none focus:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
								/>
							</div>

							<button
								type="submit"
								disabled={isLoading}
								class="mt-4 w-full bg-white text-black font-bold uppercase py-4 border-[3px] border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] transition-all duration-200 hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-[1px_1px_0_#000] hover:bg-yellow-300 disabled:opacity-50"
							>
								{isLoading ? 'Création...' : 'Créer mon compte'}
							</button>
						</form>
					{/if}
				</div>
			</div>
		</div>
	</div>
</section>
